name: GitHub Snake Game

on:
  # Run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual trigger
  workflow_dispatch:
  # Run when pushing to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      # Step 2: Generate GitHub Contributions Snake Animations
      - name: Generate GitHub Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github-light
            dist/github-snake-ocean.svg?color_snake=#ff7b00&color_dots=#facc15,#f97316,#ea580c,#c2410c
            dist/github-snake-rainbow.svg?color_snake=rainbow&color_dots=#ff0000,#ff7300,#ffea00,#00ff00,#007bff,#5a00ff,#ff00ea

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Step 3: Deploy to Output Branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update GitHub Snake Animation [skip ci]"
